spring:
  application:
    name: ecommerce-backend
  
  datasource:
    url: jdbc:h2:mem:shrihari
    username: root
    password: Amanrana@123
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  flyway:
    enabled: false
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

server:
  port: 8080

app:
  jwt:
    secret: mySecretKey123456789012345678901234567890
    expiration: 86400
    refresh-expiration: 604800
  
  cors:
    allowed-origins: http://localhost:3000,http://localhost:8080,http://127.0.0.1:5500
  
  traffic-generator:
    enabled: true

logging:
  level:
    com.ecommerce: DEBUG